### ISSUE TITLE
Scan issue on PM80

### ISSUE THREAD

**Issue by louisdup** [DevAndroidPointMobile/pointmobile_scanner#3]
Error in logs when scanning PDF417 barcode .
Let me know if you need more info ?

D/ScannerFlutterPlugin( 8860): [onReceive]
D/ScannerFlutterPlugin( 8860): [onReceive] INTENT_EVENT
D/ScannerFlutterPlugin( 8860): 1. result: true
D/ScannerFlutterPlugin( 8860): 2. bytes length: 27
D/ScannerFlutterPlugin( 8860): 3. bytes value: [B@b16346b
D/ScannerFlutterPlugin( 8860): 4. decoding length: 27
D/ScannerFlutterPlugin( 8860): 5. decoding value: This is a PDF417 by TEC-IT
D/ScannerFlutterPlugin( 8860): 6. symbol name: PDF417
D/ScannerFlutterPlugin( 8860): 7. symbol id: 65
D/ScannerFlutterPlugin( 8860): 8. symbol type: 45
D/ScannerFlutterPlugin( 8860): 9. decoding letter: 76
D/ScannerFlutterPlugin( 8860): 10.decoding modifier: 50
D/ScannerFlutterPlugin( 8860): 11.decoding time: 141
W/System.err( 8860): java.lang.NullPointerException: Attempt to get length of null array
W/System.err( 8860): 	at android.util.Base64.encode(Base64.java:494)
W/System.err( 8860): 	at android.util.Base64.encodeToString(Base64.java:456)
W/System.err( 8860): 	at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin._onDecode(PointmobileScannerPlugin.java:233)
W/System.err( 8860): 	at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin.access$200(PointmobileScannerPlugin.java:27)
W/System.err( 8860): 	at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin$ScanResultReceiver.onReceive(PointmobileScannerPlugin.java:78)
W/System.err( 8860): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
W/System.err( 8860): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 8860): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 8860): 	at android.os.Looper.loop(Looper.java:148)
W/System.err( 8860): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err( 8860): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8860): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err( 8860): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by DevAndroidPointMobile** [comment]
Dear Luis,

 

Could you share your device information refer to below link?

http://post.solution-pointmobile.co.kr:8040/display/faq/DevInfo+%3A+How+to+Get+Device+Information+File

Thanks and best regards.

Samuel Seo I Point Mobile Co., Ltd. I  <http://www.pointmobile.co.kr/> www.pointmobile.com

 <http://post.solution-pointmobile.co.kr:8040/> 

Mobile:+82 10 7240 5520 I Skype : gizerkorea

 

From: louisdup ***@***.***> 
Sent: Wednesday, November 27, 2024 6:51 PM
To: DevAndroidPointMobile/pointmobile_scanner ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DevAndroidPointMobile/pointmobile_scanner] Scan issue on PM80 (Issue #3)

 

Error in logs when scanning PDF417 barcode .
Let me know if you need more info ?

D/ScannerFlutterPlugin( 8860): [onReceive]
D/ScannerFlutterPlugin( 8860): [onReceive] INTENT_EVENT
D/ScannerFlutterPlugin( 8860): 1. result: true
D/ScannerFlutterPlugin( 8860): 2. bytes length: 27
D/ScannerFlutterPlugin( 8860): 3. bytes value: ***@***.***
D/ScannerFlutterPlugin( 8860): 4. decoding length: 27
D/ScannerFlutterPlugin( 8860): 5. decoding value: This is a PDF417 by TEC-IT
D/ScannerFlutterPlugin( 8860): 6. symbol name: PDF417
D/ScannerFlutterPlugin( 8860): 7. symbol id: 65
D/ScannerFlutterPlugin( 8860): 8. symbol type: 45
D/ScannerFlutterPlugin( 8860): 9. decoding letter: 76
D/ScannerFlutterPlugin( 8860): 10.decoding modifier: 50
D/ScannerFlutterPlugin( 8860): 11.decoding time: 141
W/System.err( 8860): java.lang.NullPointerException: Attempt to get length of null array
W/System.err( 8860): at android.util.Base64.encode(Base64.java:494)
W/System.err( 8860): at android.util.Base64.encodeToString(Base64.java:456)
W/System.err( 8860): at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin._onDecode(PointmobileScannerPlugin.java:233)
W/System.err( 8860): at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin.access$200(PointmobileScannerPlugin.java:27)
W/System.err( 8860): at com.plugin.flutter.pointmobile_scanner.PointmobileScannerPlugin$ScanResultReceiver.onReceive(PointmobileScannerPlugin.java:78)
W/System.err( 8860): at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
W/System.err( 8860): at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 8860): at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 8860): at android.os.Looper.loop(Looper.java:148)
W/System.err( 8860): at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err( 8860): at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8860): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err( 8860): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by louisdup** [comment]
Issue found, Thanks
